# Generated by Django 3.2.9 on 2021-11-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='images')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='applications.application')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
