# Generated by Django 3.2.9 on 2021-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skilltype_static_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltype',
            name='static_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
